from ursina import *

# Game Settings
WINDOW_TITLE = "FPS Game"
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
FULLSCREEN = False
VSYNC = True
DEVELOPMENT_MODE = True

# Player Settings
PLAYER_HEIGHT = 2
PLAYER_SPEED = 6
PLAYER_RUNNING_SPEED = 12
PLAYER_JUMP_HEIGHT = 0.3
PLAYER_MASS = 1

# Camera Settings
MOUSE_SENSITIVITY = Vec2(40, 40)
FOV = 90
CAMERA_MIN_ANGLE = -90
CAMERA_MAX_ANGLE = 90

# Colors
SKYBOX_COLOR = color.rgb(128, 178, 255)
GROUND_COLOR = color.rgb(160, 160, 160)